name: event-platform
services: 
  db: 
    image: postgres:18
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: event-platform
      POSTGRES_USER: event-platform
      POSTGRES_PASSWORD: stonybrook123
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "event-platform"]
    volumes: 
      - db-data:/var/lib/postgresql

  cache: 
    image: redis
    restart: always
    ports:
      - "6379:6379"

  api: 
    build: 
      context: .
      dockerfile: docker/api.Dockerfile
    env_file: .env.docker
    ports:
      - "8080:8080"
    depends_on: 
      db:
        condition: service_healthy
      cache:
        condition: service_started

  consumer: 
    build: 
      context: .
      dockerfile: docker/consumer.Dockerfile
    env_file: .env.docker
    depends_on: 
      db:
        condition: service_healthy
      cache:
        condition: service_started

  fraud-consumer: 
    build: 
      context: .
      dockerfile: docker/fraud-consumer.Dockerfile
    env_file: .env.docker
    depends_on: 
      db:
        condition: service_healthy
    

volumes:
  db-data: